/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = number;
export type Slug = string;
export type Query = string;
export type GeneratedAt = string;
export type SourcePin = string;
export type Name = string;
/**
 * Only the two states something actually produces today.
 *
 * No `blocked`/`skipped`/`failed` member exists until a stage emits one — ADR-0013's
 * "no infrastructure without a demonstrated consumer".
 */
export type StageStatus = "completed" | "not_implemented";
export type NIn = number;
export type NOut = number;
export type UnitIn = string;
export type UnitOut = string;
export type Note = string | null;
export type Stages = StageReport[];
export type Key = string;
export type ConceptNames = string[];
export type PaperIds = string[];
export type Rank = number;
export type Matched = number;
export type Proximity = number | null;
export type Label = string | null;
export type Clusters = FixtureCluster[];
export type Answer = string;
export type Title = string;
export type Journal = string | null;
export type Year = number | null;
export type Doi = string | null;
export type Pmid = string | null;
export type License = string | null;
export type LicenseTier = string;
export type ExtractionAllowed = boolean;
export type DefectId = string;
export type Anchor = string;
export type Headline = string;
export type Reason = string;
export type Findings = FixtureFinding[];

/**
 * One frozen run, sanitised for publication.
 */
export interface FixtureRun {
  schema_version: SchemaVersion;
  slug: Slug;
  query: Query;
  generated_at: GeneratedAt;
  source_pin: SourcePin;
  stages: Stages;
  clusters: Clusters;
  answer: Answer;
  papers: Papers;
  findings: Findings;
}
/**
 * One stage's accounting, including what it dropped and why.
 *
 * Lives in PipelineState rather than only in the printed report so the JSON dump carries
 * it too: `contradictions: []` alone is indistinguishable from "ran and found nothing",
 * and a machine reader must be able to tell those apart.
 *
 * `dropped` and `noted` are NOT interchangeable. `dropped` is what this stage REMOVED, in
 * the unit it consumes; `noted` is what it observed and passed through. Conflating them
 * made the first rendered ledger misreport: `no_abstract`, `zero_findings` and
 * `entity_unlinked` remove nothing, yet all three printed as "dropped N".
 *
 * `unit_in`/`unit_out` exist because stages legitimately change unit -- 20 papers in, 412
 * entities out -- and an undeclared change reads as impossible growth. Where the two units
 * match, the ledger is checkable: n_in - sum(dropped) == n_out.
 */
export interface StageReport {
  name: Name;
  status: StageStatus;
  n_in: NIn;
  n_out: NOut;
  unit_in?: UnitIn;
  unit_out?: UnitOut;
  dropped?: Dropped;
  noted?: Noted;
  note?: Note;
  [k: string]: unknown;
}
export interface Dropped {
  [k: string]: number;
}
export interface Noted {
  [k: string]: number;
}
/**
 * One cluster as displayed: identity, membership, and why it ranks where it does.
 */
export interface FixtureCluster {
  key: Key;
  concept_names: ConceptNames;
  paper_ids: PaperIds;
  rank: Rank;
  matched: Matched;
  proximity: Proximity;
  label?: Label;
}
export interface Papers {
  [k: string]: PaperStub;
}
/**
 * Citation metadata and licence facts. NEVER text.
 *
 * `license` and `doi` are not optional decoration: every tier the gate allows is a Creative
 * Commons licence and every one of them REQUIRES ATTRIBUTION, while the synthesis stage's own
 * ledger note says citation assembly is not yet built. The viewer has to supply what the
 * pipeline does not, and it can only do that if the fixture carries it.
 */
export interface PaperStub {
  title: Title;
  journal?: Journal;
  year?: Year;
  doi?: Doi;
  pmid?: Pmid;
  license?: License;
  license_tier: LicenseTier;
  extraction_allowed: ExtractionAllowed;
}
/**
 * A defect pinned to this run, quoting the adjudication rather than paraphrasing it.
 */
export interface FixtureFinding {
  defect_id: DefectId;
  anchor: Anchor;
  headline: Headline;
  reason: Reason;
}
