/**
 * The four committed runs, loaded and checked at build time.
 *
 * Fixtures are generated by `uv run python -m biolit_evals.fixture_export` and are never
 * edited by hand. Their types come from the Python models' own JSON Schema
 * (`npm run gen:types`), not from inferring over sample files.
 */
import type { FixtureCluster, FixtureRun, StageReport } from "./fixture-types";

export type { FixtureCluster, FixtureFinding, FixtureRun, PaperStub, StageReport } from "./fixture-types";

/** The only schema version this site knows how to render. Anything else fails the build. */
const UNDERSTOOD_SCHEMA_VERSION = 1;

/**
 * Presentation order, and one line on what to look at in each run. This is site copy about
 * WHERE to look, deliberately not a claim about a defect: defect callouts come only from
 * `fixture.findings`, which the Python generator refuses to write unless the run's own data
 * shows them.
 *
 * ⚠️ Each note is a claim about a live retrieval, and live PubMed returns a different paper set
 * on a different day. So each carries the predicate that makes it true, checked against the
 * fixture: a regeneration that falsifies a note fails instead of publishing it.
 */
interface RunNote {
  text: string;
  holds: (run: FixtureRun) => boolean;
}

const tied = (a: FixtureCluster, b: FixtureCluster) =>
  a.matched === b.matched && a.proximity === b.proximity;

export const RUN_NOTES: Record<string, RunNote> = {
  "statins-rhabdomyolysis": {
    text: "The question names a drug class. Several clusters carry a single member of it, atorvastatin, and are kept because of that membership (ADR-0022).",
    holds: (run) => run.clusters.some((c) => c.concept_names.includes("Atorvastatin")),
  },
  "isotretinoin-depression": {
    text: "The question asks about depression, and no cluster carries depression itself. The nearest carry broader or neighbouring MeSH concepts, and the largest cluster, about acne, ranks below them.",
    holds: (run) => {
      const noDepression = !run.clusters.some((c) =>
        c.concept_names.some((name) => /depress/i.test(name)),
      );
      const largest = [...run.clusters].sort((a, b) => b.paper_ids.length - a.paper_ids.length)[0];
      return (
        noDepression &&
        largest !== undefined &&
        /acne/i.test(largest.concept_names.join(" ")) &&
        largest.rank > 1
      );
    },
  },
  "cisplatin-nephrotoxicity": {
    text: "Only the drug half of this question ever linked to a concept, so no cluster's disease side has anything to be near. The ranker's two signals tie across every cluster, the order falls back to MeSH id, and the cluster the annotation marked as answering the question lands last.",
    holds: (run) => {
      const [first, ...rest] = run.clusters;
      const answers = run.clusters.filter((c) => c.label === "answers");
      return (
        first !== undefined &&
        run.clusters.length > 1 &&
        rest.every((c) => tied(first, c)) &&
        queryConcepts(run).length === 1 &&
        answers.length === 1 &&
        answers[0]!.rank === run.clusters.length
      );
    },
  },
  "metformin-lactic-acidosis": {
    text: "The select stage does visible work here, dropping clusters that do not touch the question.",
    holds: (run) => (stageByName(run, "select")?.dropped?.["off_query"] ?? 0) > 0,
  },
};

const modules = import.meta.glob<{ default: unknown }>("../fixtures/*.json", { eager: true });

/** Check a loaded fixture before anything renders it. Throws; never renders partially. */
export function validateFixture(path: string, raw: unknown): FixtureRun {
  const fileSlug = path.replace(/^.*\/(.+)\.json$/, "$1");
  if (typeof raw !== "object" || raw === null) {
    throw new Error(`${path}: not a JSON object`);
  }
  const run = raw as Partial<FixtureRun>;
  if (run.schema_version !== UNDERSTOOD_SCHEMA_VERSION) {
    throw new Error(
      `${path}: schema_version ${String(run.schema_version)} is not ${UNDERSTOOD_SCHEMA_VERSION}. ` +
        "Refusing to render a fixture this site does not understand; regenerate the types " +
        "(`npm run gen:types`) and update the components first.",
    );
  }
  if (run.slug !== fileSlug) {
    throw new Error(`${path}: slug ${String(run.slug)} does not match its filename`);
  }
  for (const field of ["stages", "clusters", "findings"] as const) {
    if (!Array.isArray(run[field])) throw new Error(`${path}: missing ${field}`);
  }
  return run as FixtureRun;
}

const loaded = Object.entries(modules).map(([path, mod]) => validateFixture(path, mod.default));
const bySlug = new Map(loaded.map((run) => [run.slug, run]));

const missing = Object.keys(RUN_NOTES).filter((slug) => !bySlug.has(slug));
const unexpected = [...bySlug.keys()].filter((slug) => !(slug in RUN_NOTES));
if (missing.length || unexpected.length) {
  throw new Error(
    `fixtures and RUN_NOTES disagree. Missing fixtures: [${missing.join(", ")}]. ` +
      `Fixtures with no entry in RUN_NOTES: [${unexpected.join(", ")}].`,
  );
}

/**
 * The concepts the question resolved to, read from `select`'s own note.
 *
 * They are not a field of their own, and this site does not re-resolve them: the note is what
 * the stage said it filtered on, so it is the only honest source. Empty when absent.
 */
export function queryConcepts(run: FixtureRun): string[] {
  const note = stageByName(run, "select")?.note ?? "";
  const match = /with the question \(([^)]*)\)/.exec(note);
  return match?.[1] ? match[1].split(",").map((term) => term.trim()) : [];
}

/** True where the ranker cannot separate a cluster from the one ranked directly above it. */
export function tiedWithPrevious(run: FixtureRun, cluster: FixtureCluster): boolean {
  const above = run.clusters.find((c) => c.rank === cluster.rank - 1);
  return above !== undefined && tied(above, cluster);
}

/** Throw, naming the run, if any note is no longer true of its fixture. */
export function assertNotesHold(runs: FixtureRun[]): void {
  for (const run of runs) {
    const note = RUN_NOTES[run.slug];
    if (note && !note.holds(run)) {
      throw new Error(
        `${run.slug}: its RUN_NOTES text is no longer true of the committed fixture ` +
          `(generated ${run.generated_at}). Rewrite the note for this retrieval; do not publish it.`,
      );
    }
  }
}

/** All runs, in presentation order. */
export const RUNS: FixtureRun[] = Object.keys(RUN_NOTES).map((slug) => bySlug.get(slug)!);
assertNotesHold(RUNS);

/** A stage whose units match is checkable: n_in - sum(dropped) == n_out. */
export function isCheckable(stage: StageReport): boolean {
  return (stage.unit_in ?? "") === (stage.unit_out ?? "");
}

export function stageByName(run: FixtureRun, name: string): StageReport | undefined {
  return run.stages.find((stage) => stage.name === name);
}

export interface LedgerSum {
  n_in: number;
  terms: { reason: string; count: number }[];
  n_out: number;
  /** False would be a ledger contradicting itself; the Python generator refuses to write one. */
  balances: boolean;
}

/**
 * `n_in − each drop = n_out`, for a stage whose units match. Null where the unit changes,
 * because a subtraction across units is meaningless and would read as impossible growth.
 */
export function ledgerArithmetic(stage: StageReport): LedgerSum | null {
  if (!isCheckable(stage)) return null;
  const terms = Object.entries(stage.dropped ?? {}).map(([reason, count]) => ({ reason, count }));
  const removed = terms.reduce((sum, term) => sum + term.count, 0);
  return { n_in: stage.n_in, terms, n_out: stage.n_out, balances: stage.n_in - removed === stage.n_out };
}

/** `1 papers` -> `1 paper`. Ledger units are stored plural; this only agrees them with a count. */
export function countOf(count: number, unit: string): string {
  if (count !== 1) return `${count} ${unit}`;
  const singular = unit.endsWith("ies") ? `${unit.slice(0, -3)}y` : unit.replace(/s$/, "");
  return `${count} ${singular}`;
}

/** `cc_by_nc_nd` -> `CC BY-NC-ND`. The token is the fixture's; this only spells it. */
export function licenceLabel(token: string | null | undefined): string {
  if (!token) return "no licence";
  const [first, ...rest] = token.split("_");
  if (first !== "cc" || rest.length === 0) return token;
  return `CC ${rest.join("-").toUpperCase()}`;
}

/** Paper ids cited by the answer's clusters, in the order the clusters appear. */
export function citedPaperIds(run: FixtureRun): string[] {
  const seen = new Set<string>();
  for (const cluster of [...run.clusters].sort((a, b) => a.rank - b.rank)) {
    for (const id of cluster.paper_ids) seen.add(id);
  }
  return [...seen];
}

/** Parse a finding's anchor. The grammar is defined in `biolit_evals/fixture_findings.py`. */
export type Anchor =
  | { kind: "stage"; stage: string; reason: string }
  | { kind: "cluster"; key: string };

export function parseAnchor(anchor: string): Anchor {
  const colon = anchor.indexOf(":");
  const kind = anchor.slice(0, colon);
  const target = anchor.slice(colon + 1);
  if (kind === "stage") {
    const [stage, reason] = target.split("/dropped/");
    if (stage && reason) return { kind: "stage", stage, reason };
  }
  if (kind === "cluster" && target) return { kind: "cluster", key: target };
  throw new Error(`unparseable finding anchor ${JSON.stringify(anchor)}`);
}

export function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });
}
